# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#98c379"  # soft green-gold (good for buttons / highlights)
backgroundColor="#102418"  # deep forest green background
secondaryBackgroundColor="#1b3528"  # rich secondary green for panels / sidebars / table bg
textColor="#e6f4e4"  # pale parchment greenish-white (very readable)
font="serif"
