# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#f6a21e"  # orange-gold text and buttons
backgroundColor="#3d1b43"  # deep magenta-purple
secondaryBackgroundColor="#1a0d1d"  # dark for panels / sidebars / dataframe bg
textColor="#fef3d7"  # pale parchment / light gold text
font="serif"
