# .streamlit/config.toml

[theme]
base="dark"  # The book's style is very much dark mode themed
primaryColor="#00c0f0"  # vivid cyan (matches cover + internal designs)
backgroundColor="#121212"  # deep black/gray — not full black to avoid eyestrain
secondaryBackgroundColor="#1f1f1f"  # dark gray for panels
textColor="#f8f8f8"  # pale white/gray text for high contrast
font="serif"  # gives book/fantasy feel instead of modern sans-serif
